### ISSUE TITLE
日程の決定

### ISSUE THREAD

**Issue by takanakahiko** [prickathon/prickathon#20]

**Comment by takanakahiko** [comment]
前回KPT #11 より関連するものを抜粋

とくになし

**Comment by takanakahiko** [comment]
7月の日曜日での開催を考えています．

Tasks

- コンフリクトしているイベントを確認する
- 調整さんを建てる
- SlackやTwitterハッシュタグで告知し，回答をお願いする

**Comment by takanakahiko** [comment]
同人イベント

[キラ☆プリ☆パラダイス!](http://www.youyou.co.jp/only/kira/index.html)
- 2019/9/29(日) キラ☆プリ☆パラダイス!4（東京流通センター(TRC)）
- 2019/11/24(日) キラ☆プリ☆パラダイス!大阪3（インテックス大阪）
- 2019/8/25(日) キラ☆プリ☆パラダイス!広島2（広島産業会館）
- 2019/9/1(日) キラ☆プリ☆パラダイス!名古屋10（ポートメッセなごや）
- 2019/9/22(日) キラ☆プリ☆パラダイス!札幌6（つどーむ）

[オン・ザ・ステージ](http://prittypiggy328.sakura.ne.jp/ots/)
- なし

[プリズム☆ジャンプ](http://www.puniket.com/rizumu/)
- なし(本日の終了後に発表あるかもなの...?)

**Comment by takanakahiko** [comment]
エンジニア向けカンファレンスやイベント

- 7/17~19 Open Source Summit Japan (虎ノ門ヒルズフォーラム)
- 7/22~23 CloudNativeDays (虎ノ門ヒルズフォーラム)
- (ほかあるかも...追記お願いします)

**Comment by yumechi** [comment]
エンジニア無向けのイベントしては

`7/27（土） 技術書同人誌博覧会 https://gishohaku.dev/`

ってイベントがあったりはします。（僕はサークル参加予定）

**Comment by yumechi** [comment]
エンジニア向けの大きめのイベントしては

* 7/6（土） BCU30 https://bcu30.jp/2019/
* 7/27（土） 技術書同人誌博覧会 https://gishohaku.dev/

ってイベントがあったりはします

**Comment by takanakahiko** [comment]
あざす！特にクリティカルな重複はないので，7月の日曜日すべてを対象にアンケートします．

**Comment by takanakahiko** [comment]
日程調査用のページを作りました
https://chouseisan.com/s?h=42ace857f5f446be8ea01f47ae51d108

**Comment by takanakahiko** [comment]
とりあえずは 7/21(日) で進めたいと思います
