### ISSUE TITLE
日程を決める

### ISSUE THREAD

**Issue by takanakahiko** [prickathon/prickathon#4]

**Comment by takanakahiko** [comment]
- 3月中...?
- ライブとかぶってないか
- 会場は確保できるか( #3 )
- 皆が参加しやすいかアンケートなりする
- 決まったら -> #2

**Comment by takanakahiko** [comment]
Pripara Friendship Tour 2019

- 2019年2月9日（土）東京公演：舞浜アンフィシアター　
- 2019年2月10日（日）東京公演：舞浜アンフィシアター
- 2019年2月23日（土）大阪公演：Zepp Osaka Bayside
- 2019年3月16日（土）大阪公演：Zepp Osaka Bayside
- 2019年4月13日（土）東京公演：舞浜アンフィシアター
- 2019年4月28日（日）東京公演：舞浜アンフィシアター

**Comment by yumechi** [comment]
2019/04/14（日） の技術書典の日もやめたほうが良さそう

**Comment by takanakahiko** [comment]
同人イベント

[キラ☆プリ☆パラダイス!](http://www.youyou.co.jp/only/kira/index.html)
- 2019/3/3(日) キラ☆プリ☆パラダイス!札幌5（札幌コンベンションセンター）
- 2019/3/24(日) キラ☆プリ☆パラダイス!名古屋9（ポートメッセなごや）
- 2019/8/25(日) キラ☆プリ☆パラダイス!広島2（広島産業会館）
- 2019/9/1(日) キラ☆プリ☆パラダイス!名古屋10（ポートメッセなごや）

[オン・ザ・ステージ](http://prittypiggy328.sakura.ne.jp/ots/)
- なし

[プリズム☆ジャンプ](http://www.puniket.com/rizumu/)
- 2019年3月31日（日）プリズム☆ジャンプ２４ 大田区産業プラザＰｉＯ
- 2019年5月19日（日）プリズム☆ジャンプ２５ 大田区産業プラザＰｉＯ

**Comment by takanakahiko** [comment]
公式イベント

- 3月24日（日）アニメジャパン2019 『キラッとプリ☆チャン』シーズン２放送直前ステージ

**Comment by takanakahiko** [comment]
3~4月日曜日情報

- 3/3(日) : 同人誌即売会(札幌)
- 3/10(日) : なし
- 3/17(日) : 前日にPFT大阪公演
- 3/24(日) : 同人誌即売会(名古屋)
- 3/31(日) : 同人誌即売会(東京)
- 4/7(日) : なし
- 4/14(日)  : 前日にPFT東京公演 / 技術書典
- 4/21(日) : なし
- 4/28(日) : PFT東京公演

**Comment by takanakahiko** [comment]
日程調査用のページを作りました
https://chouseisan.com/s?h=d8ce10a215424b55998ac9a92da8d39f

**Comment by yumechi** [comment]
(4/21 (日) は基本情報とかの試験がある日なので避けたほうがいいかも？)

**Comment by takanakahiko** [comment]
調整さん見た感じ，4/7がみなさんの都合良さそうなので，とりあえずそれで進めますね
